### ISSUE TITLE
Missing description of the key "hebdomon" of axis environment in the manual

### ISSUE THREAD

**Issue by quark67** [dTmC0945/Hebdomon-LaTeX-Document-Class#1]
At section 2.1.1 of the manual, we read in the sample code `\begin{axis}[hebdomon, ...]`, but the key `hebdomon` is not described in the manual. It is defined at line 385 of `hebdomon.cls`.

I suggest that you add a description of the key `hebdomon` in the manual.

**Comment by dTmC0945** [comment]
Thanks for letting me know. Added to the manual and added some features to the template.
